#!/bin/sh

# start pusleaudio (dont see any other way)
pulseaudio &

# set root pointer
xsetroot -cursor_name left_ptr

# polybar
polybar onsie &

# feh background
~/.fehbg &

# key bindings
sxhkd &

# unclutter (hides mouse while typing)
unclutter -idle 2 &

# picom
picom -b

# start libinput-gestures
libinput-gestures-setup start

# start redshift
redshift -t 6500:4900 -l 3.2476811:101.74012689999999 &

# rofi greenclipboard daemon
greenclip daemon &

# start dropbox sync
dropbox start &

# Set some bsp specific stuff
bspc monitor -d 一 二 三 四 五 六 七 八

# bspwm settings
bspc config border_width 0
bspc config window_gap 5
bspc config top_padding 30
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# some window rules

# always float feh
bspc rule -a feh state=floating follow=on

# 1 > terminal
bspc rule -a kitty desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a brave desktop='^2' follow=on focus=on

# 3 > telegram
bspc rule -a kotatogram-desktop desktop='^3' follow=on focus=on

# 4 > notion
bspc rule -a notion-app desktop='^4' follow=on focus=on

# 5 > file manager
bspc rule -a Pcmanfm desktop='^5' follow=on focus=on

# 6 > office
declare -a office=(libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 8 > music
bspc rule -a spotify desktop='^8' follow=on focus=on
