#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# feh background
~/.fehbg &

# key bindings
sxhkd &

# unclutter (hides mouse while typing)
unclutter -idle 2 &

# picom
picom --experimental-backends -b

# start redshift
redshift -l 3.152815:101.703651 -t 6500:4200 &

# Set some bsp specific stuff
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# bspwm settings
bspc config border_width 0
bspc config window_gap 3
bspc config top_padding 43
bspc config right_padding 15
bspc config bottom_padding 5
bspc config left_padding 15

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

## some window rules

# always float feh
bspc rule -a feh state=floating follow=on

# 1 > terminal, code
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Code desktop='^1' follow=on focus=on
# 2 > web
bspc rule -a Google-chrome-unstable desktop='^2'
# 3 > telegram
bspc rule -a KotatogramDesktop desktop='^3' state=floating
# 4 > notion
bspc rule -a notion-app-enhanced desktop='^4' follow=on focus=on
# 5 > file manager
bspc rule -a dolphin desktop='^5' follow=on focus=on
# 6 > office
bspc rule -a libreoffice desktop='^6' follow=on focus=on
# 7 > reading
bspc rule -a okular desktop='^7' follow=on focus=on
# 8 > slack
bspc rule -a Ferdi desktop='^8' follow=off
# 0 > music, does not always work
bspc rule -a Spotify desktop='^10' state=floating follow=off


# Plasma window rules
bspc rule -a lattedock state=floating follow=on focus=on
bspc rule -a copyq state=floating follow=on focus=on
bspc rule -a plasmawindowed state=floating focus=on follow=on
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a gwenview state=floating
bspc rule -a kruler state=floating

# other applications rules
bspc rule -a persepolis state=floating
bspc rule -a smplayer layer=above state=floating sticky=on
